spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none #?
  h2:
    console.enabled: true
    console:
      path: /h2-console


  sql:
    init:
      mode: always #?
spring.jpa.defer-datasource-initialization: true #?



# H2 console: http://localhost:8080/h2-console